// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;
using System.Net.Http;

namespace Meteroid;

/// <summary>Configures a <see cref="MeteroidClient"/>. Every property has a sensible default.</summary>
public sealed partial class MeteroidClientOptions
{
    /// <summary>The name of the <see cref="System.Diagnostics.ActivitySource"/> tracing each call,
    /// to listen to with OpenTelemetry's <c>AddSource</c>.</summary>
    public const string ActivitySourceName = "Meteroid";

    /// <summary>The API base URL, else <c>METEROID_BASE_URL</c>, else the default of the API when it
    /// declares one.</summary>
    public string? BaseUrl { get; set; }

    /// <summary>The credential when the constructor gets none, else <c>METEROID_API_KEY</c>:
    /// the bearer token, and the API key of the schemes missing from <c>ApiKeys</c>.</summary>
    public string? Token { get; set; }

    /// <summary>The <see cref="Timeout"/> used when it is not set: 60 seconds.</summary>
    public static readonly TimeSpan DefaultTimeout = TimeSpan.FromSeconds(60);

    /// <summary>Bounds each attempt, body included except for event streams.
    /// <see cref="System.Threading.Timeout.InfiniteTimeSpan"/> disables it.</summary>
    public TimeSpan Timeout { get; set; } = DefaultTimeout;

    /// <summary>Retries after network failures, timeouts, 408, 429 and 5xx, with jittered backoff or
    /// <c>Retry-After</c>, for idempotent requests or those with an <c>Idempotency-Key</c> (POST
    /// requests get one). Ignored when <see cref="RetrySchedule"/> is set.</summary>
    public int MaxRetries { get; set; } = 2;

    /// <summary>The exact delay before each retry, its length the number of retries. An empty list
    /// disables retries.</summary>
    public IReadOnlyList<TimeSpan>? RetrySchedule { get; set; }

    /// <summary>Overrides the <c>User-Agent</c> header sent with every request.</summary>
    public string? UserAgent { get; set; }

    /// <summary>Middleware wrapping every HTTP attempt inside the retry loop, the first one outermost.
    /// The client takes ownership of them.</summary>
    public IList<DelegatingHandler> Handlers { get; } = new List<DelegatingHandler>();

    /// <summary>Sends the requests instead of the client's own connection pool, e.g. a configured
    /// <see cref="SocketsHttpHandler"/>. The caller keeps ownership of it.</summary>
    public HttpMessageHandler? HttpMessageHandler { get; set; }
}
